// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk32l57hc7Rmpp2tfWjCbNwzxpFjWHPg4',
    appId: '1:626287609576:web:0a34e1165153637014eb5d',
    messagingSenderId: '626287609576',
    projectId: 'dalel-f8535',
    authDomain: 'dalel-f8535.firebaseapp.com',
    storageBucket: 'dalel-f8535.appspot.com',
    measurementId: 'G-VW0Q2P0MBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD9fWUXlSDVy2pIKPHJLjU_vaphFL3QP8',
    appId: '1:626287609576:android:e8ce011677dec8ae14eb5d',
    messagingSenderId: '626287609576',
    projectId: 'dalel-f8535',
    storageBucket: 'dalel-f8535.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7OIyhPgirtyPsr-WplCNoypg7x19kOF8',
    appId: '1:626287609576:ios:f35adaad31e3628114eb5d',
    messagingSenderId: '626287609576',
    projectId: 'dalel-f8535',
    storageBucket: 'dalel-f8535.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7OIyhPgirtyPsr-WplCNoypg7x19kOF8',
    appId: '1:626287609576:ios:99dd7c90e1d4245114eb5d',
    messagingSenderId: '626287609576',
    projectId: 'dalel-f8535',
    storageBucket: 'dalel-f8535.appspot.com',
    iosBundleId: 'com.example.dalelApp.RunnerTests',
  );
}
